- analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/DeviceProfileService.scala
- analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/DeviceRegisterService.scala
- analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/experiment/ExperimentService.scala
- analytics-api-core/src/main/scala/org/ekstep/analytics/api/util/APILogger.scala
- analytics-api-core/src/main/scala/org/ekstep/analytics/api/util/RedisUtil.scala
- analytics-api/app/modules/ActorInjector.scala
- analytics-api/conf/application.conf
@SanthoshVasabhaktula @sowmya-dixit @RevathiKotla
> Issue #000 chore: Fix router config for device apis

- analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/JobAPIService.scala
- analytics-api-core/src/main/scala/org/ekstep/analytics/api/util/CacheUtil.scala
- analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestJobAPIService.scala
- analytics-api-core/src/test/scala/org/ekstep/analytics/api/util/TestCacheUtil.scala
This PR has below changes -
- Standard Data Exhaust API - super admin authentication fix
- Signed URL issue fix
> Data Exhaust API fixes

- analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/JobAPIService.scala
- analytics-api-core/src/test/resources/application.conf
> Issue #TG-931 feat: Public data exhaust API config fixes

- analytics-api-core/src/main/scala/org/ekstep/analytics/api/Model.scala
- analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/JobAPIService.scala
- analytics-api-core/src/main/scala/org/ekstep/analytics/api/util/CommonUtil.scala
- analytics-api-core/src/test/resources/application.conf
- analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestJobAPIService.scala
- analytics-api-core/src/test/scala/org/ekstep/analytics/api/util/TestCommonUtil.scala
- analytics-api/app/controllers/JobController.scala
- analytics-api/conf/routes
- analytics-api/test/JobControllerSpec.scala
> TG-931 : Merge Release 3.8.0 to Release 3.9.0 

- auto_build_deploy
This PR includes the auto build and deployment updated Jenkins file changes.
> TG-947 updated the auto build deploy JF.

- auto_build_deploy
This PR is required to enable analytics service auto build and deployment.
> TG-947 updated the auto build deploy JF

- analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/JobAPIService.scala
- analytics-api-core/src/test/resources/application.conf
- analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestJobAPIService.scala
This PR includes exhaust API request validations on batchIds limit &  empty checks.
> TG-958: Data Exhaust APIs enhancements

- analytics-api-core/src/main/scala/org/ekstep/analytics/api/Model.scala
- analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/JobAPIService.scala
- analytics-api-core/src/main/scala/org/ekstep/analytics/api/util/PostgresDBUtil.scala
- analytics-api-core/src/test/resources/application.conf
- analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestJobAPIService.scala
- analytics-api/app/controllers/JobController.scala
- analytics-api/conf/application.conf
- analytics-api/conf/routes
- analytics-api/test/JobControllerSpec.scala
- sunbird-analytics-service-distribution/pom.xml
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SC-2181" title="SC-2181" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SC-2181</a>  Create an Exhaust 'Manage' API for internal usage
</td></table>
<br />
Internal exhaust API provides a capability to search the job request, Where the user can search the request by `status`, `dataset`, `channel` & `requested date`. This API will be used only for internal purposes. 
* Software …
> SC-2181 -  Internal exhaust search API

- analytics-api-core/src/main/scala/org/ekstep/analytics/api/util/PostgresDBUtil.scala
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SC-2181" title="SC-2181" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SC-2181</a>  Create an Exhaust 'Manage' API for internal usage
</td></table>
<br />
> SC-2181 - Exhaust search api table name fix

- analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/JobAPIService.scala
- analytics-api-core/src/test/resources/application.conf
- analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestJobAPIService.scala
This PR includes fix in exhaust submit API validation failure for druid-dataset.
> Issue #TG-1017: Fix exhaust submit API validation for druid-dataset

- analytics-api-core/src/main/scala/org/ekstep/analytics/api/util/PostgresDBUtil.scala
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25825" title="SB-25825" target="_blank"><img alt="Enhancement" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10311&avatarType=issuetype" />SB-25825</a>  Some of the course exhausts reports were not listing under the course-dashboard after we requesting. 
</td></table>
<br />
> SB-25825 - Exhaust List API to get the request in Descending Order on Request Submitted Date

- analytics-api-core/src/main/scala/org/ekstep/analytics/api/util/PostgresDBUtil.scala
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25825" title="SB-25825" target="_blank"><img alt="Enhancement" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10311&avatarType=issuetype" />SB-25825</a>  Some of the course exhausts reports were not listing under the course-dashboard after we requesting. 
</td></table>
<br />
**Test …
> SB-25825 - Merging Release 4.0.0 into Release 4.1.0

- analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/JobAPIService.scala
- analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestExperimentAPIService.scala
- analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestJobAPIService.scala
- analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestJobAPIServiceFor500Error.scala
- analytics-api-core/src/test/scala/org/ekstep/analytics/api/util/TestPostgresDBUtil.scala
- analytics-api/app/controllers/JobController.scala
- analytics-api/conf/application.conf
- analytics-api/test/JobControllerSpec.scala
This PR includes proper error handling changes on data exhaust APIs incase of 500 Internal Server errors.
> Issue #TG-1057 fix: Fix the logging for the Analytics Data Exhaust APIs

- analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/JobAPIService.scala
- analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestExperimentAPIService.scala
- analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestJobAPIService.scala
- analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestJobAPIServiceFor500Error.scala
- analytics-api-core/src/test/scala/org/ekstep/analytics/api/util/TestPostgresDBUtil.scala
- analytics-api/app/controllers/JobController.scala
- analytics-api/conf/application.conf
- analytics-api/test/JobControllerSpec.scala
> Merge Release 4.1.1 to Release 4.2.0

- analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/JobAPIService.scala
> Issue #TG-1069 fix: Data Exhaust API refactoring - bug fixes

- analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/JobAPIService.scala
> Issue #TG-1100 fix: Data Exhaust API refactoring - bug fixes

- pom.xml
> Issue #TG-1154 feat: Upgrade log4j version to 2.16.0

- analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/JobAPIService.scala
- analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestJobAPIService.scala
> Fix signed URL logic for csv files

- .circleci/config.yml
- analytics-api-core/pom.xml
- analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestJobAPIService.scala
- analytics-api/pom.xml
- pom.xml
- sunbird-analytics-service-distribution/Dockerfile
> Issue #TG-1177 feat: Upgrade to Java 11 for Analytics Service

- Jenkinsfile
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28788" title="SB-28788" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28788</a>  Upgrade Sunbird Ed data products to Java 11 for security vulnerability fixes
</td></table>
<br />
* Software …
> SB-28788 -  Java 11 Changes in the Jenkins file

- auto_build_deploy
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28788" title="SB-28788" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28788</a>  Upgrade Sunbird Ed data products to Java 11 for security vulnerability fixes
</td></table>
<br />
* Software …
> SB-28788 feat: Auto Build Jenkins file update

- Jenkinsfile
- auto_build_deploy
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28788" title="SB-28788" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28788</a>  Upgrade Sunbird Ed data products to Java 11 for security vulnerability fixes
</td></table>
<br />
* Software …
> SB-28788 feat: Jenkins file update

- Jenkinsfile
- auto_build_deploy
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28788" title="SB-28788" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28788</a>  Upgrade Sunbird Ed data products to Java 11 for security vulnerability fixes
</td></table>
<br />
* Software …
> SB-28788 -  Jenkins file update

- analytics-api-core/pom.xml
- analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestJobAPIService.scala
- analytics-api/pom.xml
- analytics-api/test/DeviceControllerSpec.scala
- pom.xml
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/OB-7" title="OB-7" target="_blank"><img alt="RFC" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10322?size=medium" />OB-7</a>  Cloud storage SDK upgrade in Analytics Framework
</td></table>
<br />
> Issue #OB-7 feat: Cloud storage sdk upgrade in Analytics Service

- analytics-api-core/pom.xml
- analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestJobAPIService.scala
- analytics-api/pom.xml
- analytics-api/test/DeviceControllerSpec.scala
- pom.xml
> Merge Release 5.0.0 to Release 5.1.0

- .circleci/config.yml
> Issue #OB-39 feat: Circle CI config changes to update new repo reference URL

- analytics-api-core/src/main/scala/org/ekstep/analytics/api/service/JobAPIService.scala
- analytics-api-core/src/test/scala/org/ekstep/analytics/api/service/TestJobAPIService.scala
> #OB-45 feat: Generation of the signed url for the relative path

- analytics-api-core/pom.xml
> #0 feat: remove scala 2.11 jackson changes
